name = "Create'a Colony 2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16a43a574afb541e6d3427715617c30fd719b5de017e569d0da4db38bc0a574b"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
